Q1

In [1]:
import pandas as pd

In [4]:
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital status":["Single","Married","Single", "Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income":["125k","100k","70k","120k","95k","60k","220k","85k","75k","90k"],
    "Cheat":["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

In [5]:
df=pd.DataFrame(data)

In [6]:
print(df)

   Tid Refund Marital status Taxable Income Cheat
0    1    Yes         Single           125k    No
1    2     No        Married           100k    No
2    3     No         Single            70k    No
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No
9   10     No         Single            90k   Yes

Q2:

In [7]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital status Taxable Income Cheat
0    1    Yes         Single           125k    No
4    5     No       Divorced            95k   Yes
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No

Q3

In [8]:
print(df.iloc[3:8])

   Tid Refund Marital status Taxable Income Cheat
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes

Q3 ii)

In [13]:
print(df.iloc[4:9, 2:5])

  Marital status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

Q3 iii)

In [15]:
print(df.iloc[:,1:4])

  Refund Marital status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes        Married           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

Q4)

In [16]:
df=pd.read_csv("Iris.csv")

In [17]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q5)

In [19]:
df=df.drop(4,axis=0)

In [20]:
df.columns[3]

'PetalLengthCm'

In [21]:
df=df.drop(df.columns[3], axis=1)

In [22]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

Q6)

In [23]:
dataset={
    "Employee_ID":[101,102,103,104,105],
    "Name":["Alice","Bob","Charlie","Diana","Edward"],
    "Department":["HR","IT","IT","Marketing","Sales"],
    "Age":[29,34,41,28,38],
    "Salary":[50000,70000,65000,55000,60000],
    "Years_of_experience":[4,8,10,3,12],
    "Joining_Date":["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender":["Female","Male","Male","Female","Male"],
    "Bonus":[5000,7000,6000,4500,5000],
    "Rating":[4.5,4.0,3.8,4.7,3.5]
}

In [26]:
df=pd.DataFrame(dataset)

In [32]:
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

a)

In [28]:
df.shape

(5, 10)

b)

In [33]:
df.info

<bound method DataFrame.info of    Employee_ID     Name Department  Age  Salary  Years_of_experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5  >

c)

In [34]:
print(df.describe())

       Employee_ID        Age       Salary  Years_of_experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

d)

In [35]:
print(df.head(5))

   Employee_ID     Name Department  Age  Salary  Years_of_experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [36]:
print(df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

e) i)

In [40]:
average_salary=(df["Salary"].mean())
print(average_salary)

60000.0

e)ii)

In [41]:
total_bonus=(df["Bonus"].sum())
print(total_bonus)

27500

e)iii)

In [42]:
min_age=(df["Age"].min())
print(min_age)

28

e)iv)

In [43]:
max_rating=(df["Rating"].max())
print(max_rating)

4.7

 Q6 f)

In [46]:
sorted_df=df.sort_values(by="Salary",ascending=False)
print(sorted_df)

   Employee_ID     Name Department  Age  Salary  Years_of_experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

g)

In [50]:
def categorize(Rating):
    if Rating >= 4:
        return "Excellent"
    elif Rating >= 3:
        return "Good"
    else:
        return "Needs Improvement"

df["Performance_Category"] = df["Rating"].apply(categorize)

In [51]:
print(df.head())

   Employee_ID     Name Department  Age  Salary  Years_of_experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance_Category
0   2020-03-15  Female   5000     4.5            Excellent
1   2017-07-19    Male   7000     4.0            Excellent
2   2013-06-01    Male   6000     3.8                 Good
3   2021-02-10  Female   4500     4.7            Excellent
4   2010-11-25    Male   5000     3.5                 Good

Q6) h)

In [54]:
df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

Q6) i)

In [55]:
df.rename(columns={"Employee_ID": "ID"}, inplace=True)

In [56]:
print(df.columns)

Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Years_of_experience',
       'Joining_Date', 'Gender', 'Bonus', 'Rating', 'Performance_Category'],
      dtype='object')

Q6 j) i)

In [58]:
result = df[df["Years_of_experience"] > 5]

print(result)

    ID     Name Department  Age  Salary  Years_of_experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0            Excellent
2   Male   6000     3.8                 Good
4   Male   5000     3.5                 Good

j)ii)

In [59]:
result = df[df["Department"] == "IT"]

print(result)

    ID     Name Department  Age  Salary  Years_of_experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0            Excellent
2   Male   6000     3.8                 Good

Q6) k)

In [60]:
df["Tax"] = df["Salary"] * 0.10

In [61]:
print(df)

    ID     Name Department  Age  Salary  Years_of_experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance_Category     Tax
0  Female   5000     4.5            Excellent  5000.0
1    Male   7000     4.0            Excellent  7000.0
2    Male   6000     3.8                 Good  6500.0
3  Female   4500     4.7            Excellent  5500.0
4    Male   5000     3.5                 Good  6000.0

Q6) L)

In [64]:
df.to_csv("modified_employee_data.csv",index=False)